### ISSUE TITLE
fix VelmaBot update language

### ISSUE THREAD

**Issue by lisabettefay** [MoralCode/velmabot#6]
Please change the VelmaBot announcement to randomly rotate the following:

`There are XX locations that need to be matched!` (default if only one message is possible)

`Looks like there are XX locations to be matched right now!`

`Psst! It's Velma o'clock! XX locations need matching!`

**Comment by MoralCode** [comment]
ooh i like that idea! i was also thinking of putting it in a configuration file of some kind so messages can be changed on-the fly without restarting the whole bot

**Comment by MoralCode** [comment]
For anyone who wants to take a crack at implementing this, my plan was to create a text file within the bots `/data` folder that contains a list of these strings. [Pythons string formating](https://docs.python.org/3/tutorial/inputoutput.html) could then be used to insert predefined variables in the middle of the strings where things like the number of sites to match could be inserted

**Comment by MoralCode** [comment]
Complete as of ec8006c78ca7399f03aea85087929d245db624bf
